version: '3'

services:
  geoserver:
    hostname: geoserver
    container_name: geoserver
    image: kartoza/geoserver
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      # - INITIAL_MEMORY=2G
      # - MAXIMUM_MEMORY=4G
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - ./files:/home/data
    ports:
      - "8080:8080"
    networks:
      - net_geoserver

  postgis:
    hostname: postgis
    container_name: postgis
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - net_geoserver

networks:
  net_geoserver:
    driver: bridge

volumes:
  geoserver-data:
  postgres-data: